#!/bin/bash

REPO_NAME="$1"
mkdir -p "$REPO_NAME"
cd "$REPO_NAME" || return
REPO_NAME="$(basename "$REPO_NAME")"

read -r -d '' GITIGNORE <<'EOF'
# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
*$py.class

# C extensions
*.so

# Distribution / packaging
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg
MANIFEST

# PyInstaller
#  Usually these files are written by a python script from a template
#  before PyInstaller builds the exe, so as to inject date/other infos into it.
*.manifest
*.spec

# Installer logs
pip-log.txt
pip-delete-this-directory.txt

# Unit test / coverage reports
htmlcov/
.tox/
.coverage
.coverage.*
.cache
nosetests.xml
coverage.xml
*.cover
.hypothesis/
.pytest_cache/

# Translations
*.mo
*.pot

# Django stuff:
*.log
local_settings.py
db.sqlite3

# Flask stuff:
instance/
.webassets-cache

# Scrapy stuff:
.scrapy

# Sphinx documentation
docs/_build/

# PyBuilder
target/

# Jupyter Notebook
.ipynb_checkpoints

# pyenv
.python-version

# celery beat schedule file
celerybeat-schedule

# SageMath parsed files
*.sage.py

# Environments
.env
.venv
env/
venv/
ENV/
env.bak/
venv.bak/

# Spyder project settings
.spyderproject
.spyproject

# Rope project settings
.ropeproject

# mkdocs documentation
/site

# mypy
.mypy_cache/
EOF

read -r -d '' SETUP_PY <<EOF
from setuptools import setup
import re


def readme():
    with open('README.md') as f:
        return f.read()


def get_version():
    version_pattern = re.compile(r'(?<=\[)\d+\.\d+\.\d+(?=\])')
    with open('CHANGELOG.md') as f:
        return version_pattern.findall(f.read())[-1]


setup(name='$REPO_NAME',
      version=get_version(),
      description='The description',
      long_description=readme(),
      url='http://github.com/ptutak/$REPO_NAME',
      author='Piotr Tutak',
      author_email='piotr.tutak@email.address.com',
      packages=['$REPO_NAME'],
      install_requires=[],
      test_suite='nose.collector',
      tests_require=['nose'],
      include_package_data=True,
      zip_safe=False)
EOF

read -r -d '' CHANGELOG_MD <<EOF
# Changelog

## [0.0.1] - $(date +%Y-%m-%d)
### Added
- Initial commit
EOF

read -r -d '' README_MD <<EOF
# $REPO_NAME

[![version][version-badge]][CHANGELOG] [![license][license-badge]][LICENSE]

## Initial README.md file
- Initial commit for project $REPO_NAME
EOF

echo "$GITIGNORE" >.gitignore
echo "$SETUP_PY" >setup.py
echo "$CHANGELOG_MD" >CHANGELOG.md
echo "$README_MD" >README.md

mkdir "$REPO_NAME"
touch "$REPO_NAME/__init__.py"
mkdir "tests"
touch "tests/__init__.py"

echo "import $REPO_NAME
from unittest import TestCase


class FirstTestCase(TestCase):
    def test_first(self):
        pass" >"tests/test_$REPO_NAME.py"

echo "# $REPO_NAME
    Initial README.md for $REPO_NAME" >README.md
